### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by neuromancer** [siredmar/mdcii-engine#55]
I think people will be more interested in testing this neat re-implementation and maybe collaborate with some code if you show the current state of this reimplementation in the README. Even early screenshots are fine!

**Comment by siredmar** [comment]
Hi!
Thanks for the issue. You are right. As this project originally started as a fork from roybaer/mdcii-engine i am currently in the process of cleaning up things (eliminiate errors and warnings, translate to english). In that process i will add some media files.
For now you can see this video for an older state
https://youtu.be/1Nw7DcvG0gk

Currently scenario loading is rudimentary added which needs some improvements.

Just curious: how did you notice this project?

**Comment by neuromancer** [comment]
> Currently scenario loading is rudimentary added which needs some improvements.

That's quite impressive still.

> Just curious: how did you notice this project?

I regularly search for classic games re-implementations engines in Github (sorting by activity). Btw, you should add proper tags to you repository to make it easier to discover.

**Comment by siredmar** [comment]
Added a youtube playlist showing the current state as it goes. 
See Readme for furher information.
